title: Open-sensor-platform
description: Open Sensor Platform project
google_analytics: open sensor platform, internet of things, iot, wearables, wearable, sensor hub, sensor, sensors, embedded sensor
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
